### ISSUE TITLE
CLIENT write homeView.html

### ISSUE THREAD

**Issue by tepidLatte** [TepidLatteGreenfield/tepidLatte2#46]

**Comment by brianronaghan** [comment]
displays all polls associated with a viewer and separates them into polls they created and polls they've been sent. ALSO: sorts opposite by date created (newest first). Additionally, when the USER clicks a poll, this viewer will have to call a method that CHANGES the current poll id on the poll factory AND redirects to the poll view. (this is confusing, whoever takes this, let's talk it all.)
